#!/usr/bin/env python3
import os
import py_compile

# Get the Python file name from the envit variable
py_filename = os.getenv('PYFILE')

# Check if the environment variable is set
if py_filename:
    # Add the '.pyc' extension to the output file name
    pyc_filename = py_filename + 'c'

    # Compile the Python file
    py_compile.compile(py_filename, cfile=pyc_filename, doraise=True)

    print(f"Compiling {py_filename} ...")
else:
    print("Environment variable PYFILE is not set.")
